# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Ansys\Намотка\Pyside2\UI\Geometry.ui',
# licensing of 'D:\Ansys\Намотка\Pyside2\UI\Geometry.ui' applies.
#
# Created: Mon May  4 19:11:08 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(696, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(696, 710))
        MainWindow.setMaximumSize(QtCore.QSize(696, 710))
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(5, 30, 78, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(5, 80, 78, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 120, 81, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 140, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 140, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 30, 78, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 170, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 30, 78, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 120, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 30, 78, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(200, 170, 120, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 30, 78, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 250, 696, 431))
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 680, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.lineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Радиус бака, мм", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Высота цилидрической части, мм", None, -1))
        self.lineEdit_2.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Верхнее днище", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Нижнее днище", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Сфера", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Конус", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Сфера", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Конус", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Параметр", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Высота сферы, мм", None, -1))
        self.lineEdit_3.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Параметр", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Высота сферы, мм", None, -1))
        self.lineEdit_4.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Параметр", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Высота конуса, мм", None, -1))
        self.lineEdit_5.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Параметр", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Высота конуса, мм", None, -1))
        self.lineEdit_6.setText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Контур бака", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Применить", None, -1))

