# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Ansys\Намотка\Pyside2\UI\Main.ui',
# licensing of 'D:\Ansys\Намотка\Pyside2\UI\Main.ui' applies.
#
# Created: Wed May 13 15:13:53 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(450, 20, 31, 23))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setAutoRepeatDelay(0)
        self.pushButton.setAutoRepeatInterval(100)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 20, 31, 23))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setAutoRepeat(False)
        self.pushButton_5.setAutoRepeatInterval(100)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 20, 31, 23))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setChecked(False)
        self.pushButton_6.setAutoRepeat(True)
        self.pushButton_6.setAutoRepeatDelay(0)
        self.pushButton_6.setAutoRepeatInterval(100)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 20, 31, 23))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setChecked(False)
        self.pushButton_7.setAutoRepeat(True)
        self.pushButton_7.setAutoRepeatDelay(0)
        self.pushButton_7.setAutoRepeatInterval(100)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 20, 31, 23))
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setChecked(False)
        self.pushButton_8.setAutoRepeat(True)
        self.pushButton_8.setAutoRepeatDelay(0)
        self.pushButton_8.setAutoRepeatInterval(100)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 20, 31, 23))
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setChecked(False)
        self.pushButton_9.setAutoRepeat(True)
        self.pushButton_9.setAutoRepeatDelay(0)
        self.pushButton_9.setAutoRepeatInterval(100)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        self.menu_4.setObjectName("menu_4")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.menu_4.addAction(self.action_6)
        self.menu.addAction(self.menu_4.menuAction())
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu_2.addAction(self.action_2)
        self.menu_3.addAction(self.action_5)
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "stop", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", ">", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("MainWindow", "All", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Намотка", None, -1))
        self.menu_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Вид намотки", None, -1))
        self.menu_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Геометрия", None, -1))
        self.menu_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Файл", None, -1))
        self.action_2.setText(QtWidgets.QApplication.translate("MainWindow", "Осесимметричное сечение", None, -1))
        self.action_3.setText(QtWidgets.QApplication.translate("MainWindow", "Толщина слоя по длине", None, -1))
        self.action_4.setText(QtWidgets.QApplication.translate("MainWindow", "Распределение угла намотки по длине", None, -1))
        self.action_5.setText(QtWidgets.QApplication.translate("MainWindow", "Выход", None, -1))
        self.action_6.setText(QtWidgets.QApplication.translate("MainWindow", "Геодезическая", None, -1))

